[package]
authors = ["Daniel Egger <daniel@eggers-club.de>"]
categories = [
    "embedded",
]
description = "Peripheral access API for STM32F042 microcontrollers"
documentation = "https://docs.rs/stm32f042"
keywords = [
    "no-std",
    "arm",
    "cortex-m",
    "stm32",
]
license = "0BSD"
name = "stm32f042"
repository = "https://github.com/therealprof/stm32f042"
version = "0.5.0"

[dependencies]
bare-metal = "0.1.1"
cortex-m = "0.4.3"
vcell = "0.1.0"

[dependencies.cortex-m-rt]
optional = true
version = "0.3.13"

[features]
rt = ["cortex-m-rt"]
