[package]
name = "stm32f042"
categories = ["embedded", "no-std"]
keywords = ["arm", "cortex-m", "template"]
version = "0.4.1"
authors = ["Daniel Egger <daniel@eggers-club.de>"]

[features]
default = ["rt"]
rt = []

[dependencies]
vcell = "0.1.0"
volatile-register = "0.2.0"
static-ref = "0.1.0"
bare-metal = "0.1.0"
numtoa = "0.0.7"

[dependencies.cortex-m]
version = "0.3.0"

[dependencies.cortex-m-rt]
features = ["abort-on-panic"]
version = "0.3.2"

[profile.dev]
lto = true
debug = true

[profile.release]
lto = true
debug = true
opt-level = "s"
